version: 2
updates:
# Dependabot (dependabot/dependabot-updater-bundler) is now failing to pull changes from repositories hosted on Github only. 
# It still works fine for repositories hosted on RubyGems.
# Temporary workaround is to create 2 checks: 
#    1 without pafs_core included so it can check for other dependencies
#    2 with pafs_core included so it will pass once dependabot-updater-bundler is fixed
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  target-branch: main
  ignore:
  - dependency-name: "dibble"
  - dependency-name: "pafs_core"

- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  target-branch: main
  ignore:
  - dependency-name: "dibble"
