inherit_from: .rubocop_todo.yml

inherit_gem:
  defra_ruby_style:
    - default.yml
require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

FactoryBot/ExcessiveCreateList:
  # default value of 10 is just not sufficient in order to test pagination 
  MaxAmount: 30
